### ISSUE TITLE
Remove GLFW dependency and compiling examples?

### ISSUE THREAD

**Issue by floooh** [fips-libs/fips-imgui#3]
IMHO automatically getting the GLFW import when using fips-imgui is a bit annoying, especially since it's only needed for compiling the examples.

Would anybody object if I simply remove the GLFW dependency, and the ability to compile the example code, so that fips-imgui would be a "pure" library (cc @code-disaster, @fungos)?

**Comment by fungos** [comment]
No, that is the correct thing to do IMO. I think it is useful to have some examples working as a way to validate the lib builds and run correctly, but that can be made differently.

**Comment by code-disaster** [comment]
No objections. I believe I mentioned the "hack" already I do in fips.yml to prevent GLFW from being compiled (but not from being fetched).

```
  fips-glfw:
    cond: "FIPS_NEVER"
```

**Comment by floooh** [comment]
Ok, it is done ;)
